### ISSUE TITLE
Issue with other input fields in the same div

### ISSUE THREAD

**Issue by tonini** [najlepsiwebdesigner/foundation-datetimepicker#5]
Hi,

After setting a input field as datepicker, I had to remove the `position: absolute;` definition in the `foundation-datepicker.css` file because it crashes all the before and further input fields.

``` css
.datepicker {
  display: none;
  /* position: absolute; */
  padding: 4px;
  margin-top: 1px;
  direction: ltr;
}
```

cheers
